name: Deploy

on:
  push:
    paths:
    - 'version.go'

defaults:
  run:
    working-directory: ./devtools/deploy/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Build
        run: go build
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./deploy
