name: Deploy

on:
  push:
    branches:
      - main
    paths:
    - 'version.go'

defaults:
  run:
    working-directory: ./devtools/deploy/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install lerna-changelog
        # run: yarn global add lerna-changelog https://github.com/actions/setup-node/issues/85
        run: npm install -g lerna-changelog
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Build
        run: go build
      - name: Deploy
        env:
          GITHUB_AUTH: ${{ secrets.AUTH_TOKEN }}
        run: ./deploy
