name: Deploy

on:
  push:
    branches:
      - master
    paths:
    - 'version.go'

defaults:
  run:
    working-directory: ./devtools/deploy/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn global add lerna-changelog
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Build
        run: go build
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./deploy
